# most possible constants
string  string_const=1
uint8   uint8_const=1
uint16  uint16_const=1
uint32  uint32_const=1
uint64  uint64_const=1 # 64 bit unsigned int comment
int8    int8_const=1
int16   int16_const=1
int32   int32_const=1
int64   int64_const=1
float32 float32_const=1

# fields
string  string_field
uint8   uint8_field
uint16  uint16_field
uint32  uint32_field
uint64  uint64_field
int8    int8_field
int16   int16_field
int32   int32_field
int64   int64_field
float32 float32_field
float64 float64_field
byte    byte_field
char    char_field
bool    bool_field
time    time_field
duration duration_field

# rest of the constants
float64 float64_const=1
byte    byte_const=1
char    char_const=1
bool    bool_const=1
